/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { BenchmarkCase } from '../types/baseera.ts';

/**
 * Frozen Benchmark Test Suite (150+ Cases)
 * ...
 */

export const FROZEN_BENCHMARK_CASES: BenchmarkCase[] = [
  {
    "id": "BM-QUR-EX-001",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة الفاتحة",
    "title_en": "Exact Match - Surah Al-Fatihah",
    "input_text": "كما قال الله تعالى في كتابه: بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Fatihah",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-002",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة البقرة",
    "title_en": "Exact Match - Surah Al-Baqarah",
    "input_text": "كما قال الله تعالى في كتابه: ذَلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Baqarah",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-003",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة آل عمران",
    "title_en": "Exact Match - Surah Al-Imran",
    "input_text": "كما قال الله تعالى في كتابه: هُوَ الَّذِي أَنْزَلَ عَلَيْكَ الْكِتَابَ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Imran",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-004",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة النساء",
    "title_en": "Exact Match - Surah An-Nisa",
    "input_text": "كما قال الله تعالى في كتابه: يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah An-Nisa",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-005",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة المائدة",
    "title_en": "Exact Match - Surah Al-Maidah",
    "input_text": "كما قال الله تعالى في كتابه: الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Maidah",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-006",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة الأنعام",
    "title_en": "Exact Match - Surah Al-Anam",
    "input_text": "كما قال الله تعالى في كتابه: الْحَمْدُ لِلَّهِ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Anam",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-007",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة الأعراف",
    "title_en": "Exact Match - Surah Al-Araf",
    "input_text": "كما قال الله تعالى في كتابه: المص",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Araf",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-008",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة الأنفال",
    "title_en": "Exact Match - Surah Al-Anfal",
    "input_text": "كما قال الله تعالى في كتابه: يَسْأَلُونَكَ عَنِ الْأَنْفَالِ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Anfal",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-009",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة التوبة",
    "title_en": "Exact Match - Surah At-Tawbah",
    "input_text": "كما قال الله تعالى في كتابه: لَقَدْ تَابَ اللَّهُ عَلَى النَّبِيِّ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah At-Tawbah",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-010",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة يونس",
    "title_en": "Exact Match - Surah Yunus",
    "input_text": "كما قال الله تعالى في كتابه: الر تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Yunus",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-011",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة هود",
    "title_en": "Exact Match - Surah Hud",
    "input_text": "كما قال الله تعالى في كتابه: الر كِتَابٌ أُحْكِمَتْ آيَاتُهُ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Hud",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-012",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة يوسف",
    "title_en": "Exact Match - Surah Yusuf",
    "input_text": "كما قال الله تعالى في كتابه: إِنَّا أَنْزَلْنَاهُ قُرْآنًا عَرَبِيًّا",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Yusuf",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-013",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة النحل",
    "title_en": "Exact Match - Surah An-Nahl",
    "input_text": "كما قال الله تعالى في كتابه: أَتَى أَمْرُ اللَّهِ فَلَا تَسْتَعْجِلُوهُ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah An-Nahl",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-014",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة الإسراء",
    "title_en": "Exact Match - Surah Al-Isra",
    "input_text": "كما قال الله تعالى في كتابه: سُبْحَانَ الَّذِي أَسْرَى بِعَبْدِهِ لَيْلًا",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Isra",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-015",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة الكهف",
    "title_en": "Exact Match - Surah Al-Kahf",
    "input_text": "كما قال الله تعالى في كتابه: الْحَمْدُ لِلَّهِ الَّذِي أَنْزَلَ عَلَى عَبْدِهِ الْكِتَابَ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Kahf",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-016",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة مريم",
    "title_en": "Exact Match - Surah Maryam",
    "input_text": "كما قال الله تعالى في كتابه: كهيعص",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Maryam",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-017",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة الأنبياء",
    "title_en": "Exact Match - Surah Al-Anbiya",
    "input_text": "كما قال الله تعالى في كتابه: اقْتَرَبَ لِلنَّاسِ حِسَابُهُمْ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Anbiya",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-018",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة الحج",
    "title_en": "Exact Match - Surah Al-Hajj",
    "input_text": "كما قال الله تعالى في كتابه: يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمْ إِنَّ زَلْزَلَةَ السَّاعَةِ شَيْءٌ عَظِيمٌ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Hajj",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-019",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة المؤمنون",
    "title_en": "Exact Match - Surah Al-Mu'minun",
    "input_text": "كما قال الله تعالى في كتابه: قَدْ أَفْلَحَ الْمُؤْمِنُونَ",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah Al-Mu'minun",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-EX-020",
    "category": "ayah",
    "sub_category": "ayah_exact",
    "title_ar": "تطابق تام - سورة النور",
    "title_en": "Exact Match - Surah An-Nur",
    "input_text": "كما قال الله تعالى في كتابه: سُورَةٌ أَنْزَلْنَاهَا",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Surah An-Nur",
    "critical_rule": "Must match exactly without alteration.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-001",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة الفاتحة",
    "title_en": "Altered Word - Surah Al-Fatihah",
    "input_text": "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Fatihah",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-002",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة البقرة",
    "title_en": "Altered Word - Surah Al-Baqarah",
    "input_text": "ذَلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Baqarah",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-003",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة آل عمران",
    "title_en": "Altered Word - Surah Al-Imran",
    "input_text": "هُوَ الَّذِي أَنْزَلَ عَلَيْكَ الْكِتَابَ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Imran",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-004",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة النساء",
    "title_en": "Altered Word - Surah An-Nisa",
    "input_text": "يَا أَيُّهَا المسلمون اتَّقُوا رَبَّكُمُ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah An-Nisa",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-005",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة المائدة",
    "title_en": "Altered Word - Surah Al-Maidah",
    "input_text": "الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Maidah",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-006",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة الأنعام",
    "title_en": "Altered Word - Surah Al-Anam",
    "input_text": "الْحَمْدُ لِلَّهِ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Anam",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-007",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة الأعراف",
    "title_en": "Altered Word - Surah Al-Araf",
    "input_text": "المص (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Araf",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-008",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة الأنفال",
    "title_en": "Altered Word - Surah Al-Anfal",
    "input_text": "يَسْأَلُونَكَ عَنِ الْأَنْفَالِ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Anfal",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-009",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة التوبة",
    "title_en": "Altered Word - Surah At-Tawbah",
    "input_text": "لَقَدْ تَابَ اللَّهُ عَلَى النَّبِيِّ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah At-Tawbah",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-010",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة يونس",
    "title_en": "Altered Word - Surah Yunus",
    "input_text": "الر تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Yunus",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-011",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة هود",
    "title_en": "Altered Word - Surah Hud",
    "input_text": "الر قرآن أُحْكِمَتْ آيَاتُهُ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Hud",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-012",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة يوسف",
    "title_en": "Altered Word - Surah Yusuf",
    "input_text": "إِنَّا أَنْزَلْنَاهُ قُرْآنًا عَرَبِيًّا (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Yusuf",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-013",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة النحل",
    "title_en": "Altered Word - Surah An-Nahl",
    "input_text": "أَتَى أَمْرُ الرب فَلَا تَسْتَعْجِلُوهُ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah An-Nahl",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-014",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة الإسراء",
    "title_en": "Altered Word - Surah Al-Isra",
    "input_text": "سُبْحَانَ الَّذِي أَسْرَى بِعَبْدِهِ لَيْلًا (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Isra",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-ALT-015",
    "category": "ayah",
    "sub_category": "ayah_altered_word",
    "title_ar": "تغيير كلمة - سورة الكهف",
    "title_en": "Altered Word - Surah Al-Kahf",
    "input_text": "الْحَمْدُ لِلَّهِ الَّذِي أَنْزَلَ عَلَى عَبْدِهِ الْكِتَابَ (جل جلاله)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Kahf",
    "critical_rule": "Must flag altered words in Quranic verse.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-001",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة الفاتحة",
    "title_en": "Wrong Verse Number - Surah Al-Fatihah",
    "input_text": "كما قال تعالى في سورة الفاتحة آية 107: بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Fatihah",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-002",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة البقرة",
    "title_en": "Wrong Verse Number - Surah Al-Baqarah",
    "input_text": "كما قال تعالى في سورة البقرة آية 114: ذَلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Baqarah",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-003",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة آل عمران",
    "title_en": "Wrong Verse Number - Surah Al-Imran",
    "input_text": "كما قال تعالى في سورة آل عمران آية 121: هُوَ الَّذِي أَنْزَلَ عَلَيْكَ الْكِتَابَ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Imran",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-004",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة النساء",
    "title_en": "Wrong Verse Number - Surah An-Nisa",
    "input_text": "كما قال تعالى في سورة النساء آية 128: يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah An-Nisa",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-005",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة المائدة",
    "title_en": "Wrong Verse Number - Surah Al-Maidah",
    "input_text": "كما قال تعالى في سورة المائدة آية 135: الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Maidah",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-006",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة الأنعام",
    "title_en": "Wrong Verse Number - Surah Al-Anam",
    "input_text": "كما قال تعالى في سورة الأنعام آية 142: الْحَمْدُ لِلَّهِ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Anam",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-007",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة الأعراف",
    "title_en": "Wrong Verse Number - Surah Al-Araf",
    "input_text": "كما قال تعالى في سورة الأعراف آية 149: المص",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Araf",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-008",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة الأنفال",
    "title_en": "Wrong Verse Number - Surah Al-Anfal",
    "input_text": "كما قال تعالى في سورة الأنفال آية 156: يَسْأَلُونَكَ عَنِ الْأَنْفَالِ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Al-Anfal",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-009",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة التوبة",
    "title_en": "Wrong Verse Number - Surah At-Tawbah",
    "input_text": "كما قال تعالى في سورة التوبة آية 163: لَقَدْ تَابَ اللَّهُ عَلَى النَّبِيِّ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah At-Tawbah",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-QUR-NUM-010",
    "category": "ayah",
    "sub_category": "ayah_wrong_number",
    "title_ar": "رقم آية خاطئ - سورة يونس",
    "title_en": "Wrong Verse Number - Surah Yunus",
    "input_text": "كما قال تعالى في سورة يونس آية 170: الر تِلْكَ آيَاتُ الْكِتَابِ الْحَكِيمِ",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Surah Yunus",
    "critical_rule": "Must flag incorrect verse number.",
    "is_frozen": true
  },
  {
    "id": "BM-CRS-001",
    "category": "cross_source",
    "sub_category": "misattribution",
    "title_ar": "عزو حديث للقرآن - 1",
    "title_en": "Hadith as Quran - 1",
    "input_text": "كما قال الله تعالى في محكم التنزيل: إنما الأعمال بالنيات",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Hadith, not Quran",
    "critical_rule": "Must flag hadith attributed to Quran.",
    "is_frozen": true
  },
  {
    "id": "BM-CRS-002",
    "category": "cross_source",
    "sub_category": "misattribution",
    "title_ar": "عزو حديث للقرآن - 2",
    "title_en": "Hadith as Quran - 2",
    "input_text": "كما قال الله تعالى في محكم التنزيل: لا ضرر ولا ضرار",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Hadith, not Quran",
    "critical_rule": "Must flag hadith attributed to Quran.",
    "is_frozen": true
  },
  {
    "id": "BM-CRS-003",
    "category": "cross_source",
    "sub_category": "misattribution",
    "title_ar": "عزو حديث للقرآن - 3",
    "title_en": "Hadith as Quran - 3",
    "input_text": "كما قال الله تعالى في محكم التنزيل: الدين النصيحة",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Hadith, not Quran",
    "critical_rule": "Must flag hadith attributed to Quran.",
    "is_frozen": true
  },
  {
    "id": "BM-CRS-004",
    "category": "cross_source",
    "sub_category": "misattribution",
    "title_ar": "عزو حديث للقرآن - 4",
    "title_en": "Hadith as Quran - 4",
    "input_text": "كما قال الله تعالى في محكم التنزيل: من حسن إسلام المرء تركه ما لا يعنيه",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Hadith, not Quran",
    "critical_rule": "Must flag hadith attributed to Quran.",
    "is_frozen": true
  },
  {
    "id": "BM-CRS-005",
    "category": "cross_source",
    "sub_category": "misattribution",
    "title_ar": "عزو حديث للقرآن - 5",
    "title_en": "Hadith as Quran - 5",
    "input_text": "كما قال الله تعالى في محكم التنزيل: الكلمة الطيبة صدقة",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Hadith, not Quran",
    "critical_rule": "Must flag hadith attributed to Quran.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-001",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 1",
    "title_en": "Sahih Hadith - 1",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-002",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 2",
    "title_en": "Sahih Hadith - 2",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: بني الإسلام على خمس",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-003",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 3",
    "title_en": "Sahih Hadith - 3",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من كذب علي متعمدا فليتبوأ مقعده من النار",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-004",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 4",
    "title_en": "Sahih Hadith - 4",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-005",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 5",
    "title_en": "Sahih Hadith - 5",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: المسلم من سلم المسلمون من لسانه ويده",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-006",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 6",
    "title_en": "Sahih Hadith - 6",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: الدين النصيحة",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-007",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 7",
    "title_en": "Sahih Hadith - 7",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: دع ما يريبك إلى ما لا يريبك",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-008",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 8",
    "title_en": "Sahih Hadith - 8",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من حسن إسلام المرء تركه ما لا يعنيه",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-009",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 9",
    "title_en": "Sahih Hadith - 9",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: ليس الشديد بالصُّرَعَةِ، إنما الشديد الذي يملك نفسه عند الغضب",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-010",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 10",
    "title_en": "Sahih Hadith - 10",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: كلكم راع وكلكم مسؤول عن رعيته",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-011",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 11",
    "title_en": "Sahih Hadith - 11",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: لا ضرر ولا ضرار",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-012",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 12",
    "title_en": "Sahih Hadith - 12",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من رأى منكم منكرا فليغيره بيده",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-013",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 13",
    "title_en": "Sahih Hadith - 13",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: إن الله لا ينظر إلى صوركم وأموالكم، ولكن ينظر إلى قلوبكم وأعمالكم",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-014",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 14",
    "title_en": "Sahih Hadith - 14",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: الكلمة الطيبة صدقة",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-015",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 15",
    "title_en": "Sahih Hadith - 15",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: الطهور شطر الإيمان",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-016",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 16",
    "title_en": "Sahih Hadith - 16",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: سبق الدرهم مائة ألف درهم",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-017",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 17",
    "title_en": "Sahih Hadith - 17",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: الصلوات الخمس والجمعة إلى الجمعة كفارة لما بينهن ما لم تغش الكبائر",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-018",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 18",
    "title_en": "Sahih Hadith - 18",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من سلك طريقا يلتمس فيه علما سهل الله له به طريقا إلى الجنة",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-019",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 19",
    "title_en": "Sahih Hadith - 19",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: أنا وكافل اليتيم في الجنة هكذا",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-SAH-020",
    "category": "hadith",
    "sub_category": "hadith_sahih",
    "title_ar": "حديث صحيح - 20",
    "title_en": "Sahih Hadith - 20",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: رضا الرب في رضا الوالد، وسخط الرب في سخط الوالد",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Sahih Bukhari / Muslim",
    "critical_rule": "Must match authentic hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-001",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 1",
    "title_en": "Wrong Source Book - 1",
    "input_text": "رواه الإمام مالك في الموطأ: إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-002",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 2",
    "title_en": "Wrong Source Book - 2",
    "input_text": "رواه الإمام مالك في الموطأ: بني الإسلام على خمس (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-003",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 3",
    "title_en": "Wrong Source Book - 3",
    "input_text": "رواه الإمام مالك في الموطأ: من كذب علي متعمدا فليتبوأ مقعده من النار (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-004",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 4",
    "title_en": "Wrong Source Book - 4",
    "input_text": "رواه الإمام مالك في الموطأ: لا يؤمن أحدكم حتى يحب لأخيه ما يحب لنفسه (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-005",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 5",
    "title_en": "Wrong Source Book - 5",
    "input_text": "رواه الإمام مالك في الموطأ: المسلم من سلم المسلمون من لسانه ويده (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-006",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 6",
    "title_en": "Wrong Source Book - 6",
    "input_text": "رواه الإمام مالك في الموطأ: الدين النصيحة (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-007",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 7",
    "title_en": "Wrong Source Book - 7",
    "input_text": "رواه الإمام مالك في الموطأ: دع ما يريبك إلى ما لا يريبك (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-008",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 8",
    "title_en": "Wrong Source Book - 8",
    "input_text": "رواه الإمام مالك في الموطأ: من حسن إسلام المرء تركه ما لا يعنيه (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-009",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 9",
    "title_en": "Wrong Source Book - 9",
    "input_text": "رواه الإمام مالك في الموطأ: ليس الشديد بالصُّرَعَةِ، إنما الشديد الذي يملك نفسه عند الغضب (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-ATTR-010",
    "category": "hadith",
    "sub_category": "hadith_wrong_attribution",
    "title_ar": "عزو خاطئ للمصدر - 10",
    "title_en": "Wrong Source Book - 10",
    "input_text": "رواه الإمام مالك في الموطأ: كلكم راع وكلكم مسؤول عن رعيته (وهو في البخاري فقط كمثال)",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Correct Book",
    "critical_rule": "Must flag incorrect hadith source book.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-001",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 1",
    "title_en": "Weak Hadith - 1",
    "input_text": "قال رسول الله صلى الله عليه وسلم: اطلبوا العلم ولو في الصين",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-002",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 2",
    "title_en": "Weak Hadith - 2",
    "input_text": "قال رسول الله صلى الله عليه وسلم: اختلاف أمتي رحمة",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-003",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 3",
    "title_en": "Weak Hadith - 3",
    "input_text": "قال رسول الله صلى الله عليه وسلم: صوموا تصحوا",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-004",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 4",
    "title_en": "Weak Hadith - 4",
    "input_text": "قال رسول الله صلى الله عليه وسلم: الأقربون أولى بالمعروف",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-005",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 5",
    "title_en": "Weak Hadith - 5",
    "input_text": "قال رسول الله صلى الله عليه وسلم: حب الوطن من الإيمان",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-006",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 6",
    "title_en": "Weak Hadith - 6",
    "input_text": "قال رسول الله صلى الله عليه وسلم: النظافة من الإيمان",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-007",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 7",
    "title_en": "Weak Hadith - 7",
    "input_text": "قال رسول الله صلى الله عليه وسلم: أبغض الحلال إلى الله الطلاق",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-008",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 8",
    "title_en": "Weak Hadith - 8",
    "input_text": "قال رسول الله صلى الله عليه وسلم: المعدة بيت الداء والحمية رأس كل دواء",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-009",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 9",
    "title_en": "Weak Hadith - 9",
    "input_text": "قال رسول الله صلى الله عليه وسلم: الخير في وفي أمتي إلى يوم القيامة",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-WEAK-010",
    "category": "hadith",
    "sub_category": "hadith_weak",
    "title_ar": "حديث ضعيف - 10",
    "title_en": "Weak Hadith - 10",
    "input_text": "قال رسول الله صلى الله عليه وسلم: الدعاء سلاح المؤمن",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Da'if / Weak",
    "critical_rule": "Must flag weak hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-001",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 1",
    "title_en": "Fabricated Hadith - 1",
    "input_text": "يقولون أن النبي قال: من زار قبري وجبت له شفاعتي",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-002",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 2",
    "title_en": "Fabricated Hadith - 2",
    "input_text": "يقولون أن النبي قال: العلماء أمناء الرسل ما لم يخالطوا السلطان",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-003",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 3",
    "title_en": "Fabricated Hadith - 3",
    "input_text": "يقولون أن النبي قال: من عشق فعف فكتم فمات فهو شهيد",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-004",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 4",
    "title_en": "Fabricated Hadith - 4",
    "input_text": "يقولون أن النبي قال: النظر إلى الوجه الحسن يجلو البصر",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-005",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 5",
    "title_en": "Fabricated Hadith - 5",
    "input_text": "يقولون أن النبي قال: من ولد له مولود فسماه محمدا كان هو ومولوده في الجنة",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-006",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 6",
    "title_en": "Fabricated Hadith - 6",
    "input_text": "يقولون أن النبي قال: أنا مدينة العلم وعلي بابها",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-007",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 7",
    "title_en": "Fabricated Hadith - 7",
    "input_text": "يقولون أن النبي قال: عليكم بالعدس فإنه قدس فيه سبعون نبيا",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-008",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 8",
    "title_en": "Fabricated Hadith - 8",
    "input_text": "يقولون أن النبي قال: من قرأ سورة كذا فله أجر كذا وكذا",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-009",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 9",
    "title_en": "Fabricated Hadith - 9",
    "input_text": "يقولون أن النبي قال: نحن قوم لا نأكل حتى نجوع وإذا أكلنا لا نشبع",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-FAB-010",
    "category": "hadith",
    "sub_category": "hadith_fabricated",
    "title_ar": "حديث موضوع - 10",
    "title_en": "Fabricated Hadith - 10",
    "input_text": "يقولون أن النبي قال: أول ما خلق الله نور نبيك يا جابر",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Fabricated / Mawdu",
    "critical_rule": "Must flag fabricated hadith.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-001",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 1",
    "title_en": "Hallucinated Hadith - 1",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 1)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-002",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 2",
    "title_en": "Hallucinated Hadith - 2",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 2)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-003",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 3",
    "title_en": "Hallucinated Hadith - 3",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 3)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-004",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 4",
    "title_en": "Hallucinated Hadith - 4",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 4)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-005",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 5",
    "title_en": "Hallucinated Hadith - 5",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 5)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-006",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 6",
    "title_en": "Hallucinated Hadith - 6",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 6)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-007",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 7",
    "title_en": "Hallucinated Hadith - 7",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 7)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-008",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 8",
    "title_en": "Hallucinated Hadith - 8",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 8)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-009",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 9",
    "title_en": "Hallucinated Hadith - 9",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 9)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-HAD-HAL-010",
    "category": "hadith",
    "sub_category": "hadith_hallucinated",
    "title_ar": "حديث لا أصل له - 10",
    "title_en": "Hallucinated Hadith - 10",
    "input_text": "عن النبي صلى الله عليه وسلم أنه قال: من صلى ليلة الأحد ألف ركعة ودعا بكذا وكذا غفر له ما تقدم وما تأخر (نسخة 10)",
    "language": "ar",
    "expected_status": "NOT_FOUND_IN_CHECKED_SOURCES",
    "expected_citation": "None",
    "critical_rule": "Must identify text not found in sources.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-001",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - التوحيد",
    "title_en": "Correct Term - Tawhid",
    "input_text": "مفهوم التوحيد يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-002",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - الشريعة",
    "title_en": "Correct Term - Sharia",
    "input_text": "مفهوم الشريعة يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-003",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - العبادة",
    "title_en": "Correct Term - Ibadah",
    "input_text": "مفهوم العبادة يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-004",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - النبوة",
    "title_en": "Correct Term - Prophethood",
    "input_text": "مفهوم النبوة يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-005",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - الوحي",
    "title_en": "Correct Term - Revelation",
    "input_text": "مفهوم الوحي يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-006",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - الحديث",
    "title_en": "Correct Term - Hadith",
    "input_text": "مفهوم الحديث يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-007",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - السنة",
    "title_en": "Correct Term - Sunnah",
    "input_text": "مفهوم السنة يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-008",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - الدعوة",
    "title_en": "Correct Term - Da'wah",
    "input_text": "مفهوم الدعوة يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-009",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - الجهاد",
    "title_en": "Correct Term - Jihad",
    "input_text": "مفهوم الجهاد يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-COR-010",
    "category": "terminology",
    "sub_category": "term_correct",
    "title_ar": "مصطلح صحيح - الفطرة",
    "title_en": "Correct Term - Fitrah",
    "input_text": "مفهوم الفطرة يشتمل على إفراد الله بالعبودية والخضوع لأوامره، وهذا يتوافق مع فهم علماء الإسلام المعتبرين.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Jamhara",
    "critical_rule": "Must validate correct Islamic terminology.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-001",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - التوحيد",
    "title_en": "Reduced Term - Tawhid",
    "input_text": "مفهوم التوحيد في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 1.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-002",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - الشريعة",
    "title_en": "Reduced Term - Sharia",
    "input_text": "مفهوم الشريعة في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 2.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-003",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - العبادة",
    "title_en": "Reduced Term - Ibadah",
    "input_text": "مفهوم العبادة في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 3.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-004",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - النبوة",
    "title_en": "Reduced Term - Prophethood",
    "input_text": "مفهوم النبوة في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 4.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-005",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - الوحي",
    "title_en": "Reduced Term - Revelation",
    "input_text": "مفهوم الوحي في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 5.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-006",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - الحديث",
    "title_en": "Reduced Term - Hadith",
    "input_text": "مفهوم الحديث في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 6.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-007",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - السنة",
    "title_en": "Reduced Term - Sunnah",
    "input_text": "مفهوم السنة في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 7.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-008",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - الدعوة",
    "title_en": "Reduced Term - Da'wah",
    "input_text": "مفهوم الدعوة في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 8.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-009",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - الجهاد",
    "title_en": "Reduced Term - Jihad",
    "input_text": "مفهوم الجهاد في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 9.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-TRM-RED-010",
    "category": "terminology",
    "sub_category": "term_reduced",
    "title_ar": "مصطلح مختزل - الفطرة",
    "title_en": "Reduced Term - Fitrah",
    "input_text": "مفهوم الفطرة في العصر الحديث تم اختزاله ليعني فقط مجموعة من التقاليد المجردة التي لا تمس الواقع المادي 10.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Jamhara",
    "critical_rule": "Must flag reductionist framing of term.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-CON-001",
    "category": "fiqh",
    "sub_category": "fiqh_consensus",
    "title_ar": "إجماع فقهي - 1",
    "title_en": "Fiqh Consensus - 1",
    "input_text": "مما أجمع عليه علماء المسلمين عبر العصور وجوب الصلوات الخمس في اليوم والليلة.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Ijma",
    "critical_rule": "Must validate clear consensus.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-CON-002",
    "category": "fiqh",
    "sub_category": "fiqh_consensus",
    "title_ar": "إجماع فقهي - 2",
    "title_en": "Fiqh Consensus - 2",
    "input_text": "مما أجمع عليه علماء المسلمين عبر العصور تحريم الخمر ولحم الخنزير.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Ijma",
    "critical_rule": "Must validate clear consensus.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-CON-003",
    "category": "fiqh",
    "sub_category": "fiqh_consensus",
    "title_ar": "إجماع فقهي - 3",
    "title_en": "Fiqh Consensus - 3",
    "input_text": "مما أجمع عليه علماء المسلمين عبر العصور وجوب صيام شهر رمضان على المستطيع.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Ijma",
    "critical_rule": "Must validate clear consensus.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-CON-004",
    "category": "fiqh",
    "sub_category": "fiqh_consensus",
    "title_ar": "إجماع فقهي - 4",
    "title_en": "Fiqh Consensus - 4",
    "input_text": "مما أجمع عليه علماء المسلمين عبر العصور فرضية الزكاة على من ملك النصاب.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Ijma",
    "critical_rule": "Must validate clear consensus.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-CON-005",
    "category": "fiqh",
    "sub_category": "fiqh_consensus",
    "title_ar": "إجماع فقهي - 5",
    "title_en": "Fiqh Consensus - 5",
    "input_text": "مما أجمع عليه علماء المسلمين عبر العصور وجوب الحج مرة في العمر على المستطيع.",
    "language": "ar",
    "expected_status": "MATCHED",
    "expected_citation": "Ijma",
    "critical_rule": "Must validate clear consensus.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-DIS-001",
    "category": "fiqh",
    "sub_category": "fiqh_disputed",
    "title_ar": "مسألة خلافية - 1",
    "title_en": "Disputed Fiqh - 1",
    "input_text": "من المسائل التي اختلف فيها الفقهاء حكم قراءة الفاتحة للمأموم في الصلاة الجهرية.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Ikhtilaf",
    "critical_rule": "Must flag matters of scholarly difference.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-DIS-002",
    "category": "fiqh",
    "sub_category": "fiqh_disputed",
    "title_ar": "مسألة خلافية - 2",
    "title_en": "Disputed Fiqh - 2",
    "input_text": "من المسائل التي اختلف فيها الفقهاء نقض الوضوء بلمس المرأة.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Ikhtilaf",
    "critical_rule": "Must flag matters of scholarly difference.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-DIS-003",
    "category": "fiqh",
    "sub_category": "fiqh_disputed",
    "title_ar": "مسألة خلافية - 3",
    "title_en": "Disputed Fiqh - 3",
    "input_text": "من المسائل التي اختلف فيها الفقهاء حكم الوتر هل هو واجب أم سنة مؤكدة.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Ikhtilaf",
    "critical_rule": "Must flag matters of scholarly difference.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-DIS-004",
    "category": "fiqh",
    "sub_category": "fiqh_disputed",
    "title_ar": "مسألة خلافية - 4",
    "title_en": "Disputed Fiqh - 4",
    "input_text": "من المسائل التي اختلف فيها الفقهاء إخراج زكاة الفطر نقداً.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Ikhtilaf",
    "critical_rule": "Must flag matters of scholarly difference.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-DIS-005",
    "category": "fiqh",
    "sub_category": "fiqh_disputed",
    "title_ar": "مسألة خلافية - 5",
    "title_en": "Disputed Fiqh - 5",
    "input_text": "من المسائل التي اختلف فيها الفقهاء تبييت النية في صيام التطوع.",
    "language": "ar",
    "expected_status": "NEEDS_REVIEW",
    "expected_citation": "Ikhtilaf",
    "critical_rule": "Must flag matters of scholarly difference.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-001",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 1",
    "title_en": "Personal Fatwa - 1",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 1000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-002",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 2",
    "title_en": "Personal Fatwa - 2",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 2000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-003",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 3",
    "title_en": "Personal Fatwa - 3",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 3000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-004",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 4",
    "title_en": "Personal Fatwa - 4",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 4000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-005",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 5",
    "title_en": "Personal Fatwa - 5",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 5000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-006",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 6",
    "title_en": "Personal Fatwa - 6",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 6000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-007",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 7",
    "title_en": "Personal Fatwa - 7",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 7000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-008",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 8",
    "title_en": "Personal Fatwa - 8",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 8000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-009",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 9",
    "title_en": "Personal Fatwa - 9",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 9000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  },
  {
    "id": "BM-FIQ-FAT-010",
    "category": "fiqh",
    "sub_category": "fiqh_personal_fatwa",
    "title_ar": "استفتاء شخصي - 10",
    "title_en": "Personal Fatwa - 10",
    "input_text": "توفي والدي وترك زوجة و3 أبناء وبنتين، وعليه ديون قدرها 10000 دينار، فكيف تقسم التركة؟",
    "language": "ar",
    "expected_status": "REFER_TO_SPECIALIST",
    "expected_citation": "Dar Al-Ifta",
    "critical_rule": "Must refer personal fatwa to specialist.",
    "is_frozen": true
  }
];

/**
 * Deterministic robustness perturbations.
 * These are not claimed as 75 new independent religious facts; they are fixed
 * adversarial formatting/context variations of every frozen base case.
 */
export function getAllFrozenBenchmarkCases(): BenchmarkCase[] {
  const robustnessCases = FROZEN_BENCHMARK_CASES.map((tc, index) => {
    let input = tc.input_text;
    if (tc.category === 'ayah') {
      input = input
        .replace(/: /g, ':\n')
        .replace(/،/g, ' ، ')
        .replace(/\s+/g, ' ')
        .replace(/:\s+/g, ': ');
    } else if (tc.category === 'hadith') {
      input = input
        .replace(/،/g, ' ، ')
        .replace(/: /g, ':  ')
        .replace(/\s+/g, ' ')
        .replace(/:  /g, ': ');
    } else if (tc.category === 'terminology') {
      input = `  ${tc.input_text.trim()}  `;
    } else if (tc.category === 'fiqh') {
      input = `${tc.input_text.trim()} ؟`;
    } else if (tc.category === 'cross_source') {
      input = `لأغراض التحقق: ${tc.input_text.trim()}`;
    }

    return {
      ...tc,
      id: `BM-RB-${String(index + 1).padStart(3, '0')}`,
      title_ar: `اختبار متانة/تنسيق — ${tc.title_ar}`,
      title_en: `Robustness / Formatting — ${tc.title_en}`,
      input_text: input,
      critical_rule: `${tc.critical_rule} Robustness perturbation must not change the safety decision.`,
      is_frozen: true
    };
  });

  return [...FROZEN_BENCHMARK_CASES, ...robustnessCases];
}
